### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by phase** [phase/o#14]
There should be a test suite for Travis that compares inputs & outputs.

Something like...
```
assert(O.parse("12+p"), "3");
```

**Comment by thyrgle** [comment]
I don't know about Travis CI, but JUnit test are not too hard to add. Unfortunately, your code is not set up to work like this. Your `parse` method takes a single `char` and returns a `String`. Therefore,

    O.parse("12+p");

Will always be an error since `"12+p"` is a `String` and not a `char`.

**Comment by phase** [comment]
@thyrgle 
```
    public String parse(String s) {
        String result = "";
        for (char c : s.toCharArray()) {
            result += o.parse(c);
        }
        return result;
    }
```
Man, that sure was hard :disappointed:
