### ISSUE TITLE
Switch JNI to JNA using BirdJ/JNAerator

### ISSUE THREAD

**Issue by phase** [phase/o#22]
We can use [BirdJ](https://github.com/nativelibs4java/BridJ)/[JNAerator](https://github.com/nativelibs4java/JNAerator) to gain access to the C code.

**Comment by kirbyfan64** [comment]
So I *didn't* need to write that JNI crap?

Darn. :/

**Comment by phase** [comment]
I think we'll need it for the WebIDE, cause Maven.
