### ISSUE TITLE
Operator to push a blank CodeBlock

### ISSUE THREAD

**Issue by phase** [phase/o#24]
```java
1{}{1o}?
```
If-then-else statements can be verbose when you only want to execute something depending on the value, so there should be an operator/macro that pushes a blank codeblock. `{}` -> `N`. `N` could actually be a good one (if it isn't in use atm), as it could stand for *null codeblock*.

**Comment by kirbyfan64** [comment]
Do you want me to do this one? It's pretty easy and could be done as a macro.

**Comment by phase** [comment]
I just wasn't sure on what letter/symbol we wanted to use.

**Comment by kirbyfan64** [comment]
@phase I guess `N` works. Worst comes to worse, we can always change it later.

**Comment by phase** [comment]
B͡u͜t̸ ̛w̴ha̵t a͡b̢óut b̢̦̺̜̦͙̥͍́͜a͎͕͖͚̝͉c̢͇͈̮͇͢͜k̴̵̡̥̙̙ẁ̷̰ḁ͈͍̣̬͍͎̖͝r̷͎̝͕̹̠̮͔̕d̡̩͖͔̦̘͞͝s̨̡̫̱͎̤͕ͅ ̟̤͚̮̱̘͓̱͞ç̰͙̮̥̫͢o̫̹̼͚̗̯̕͢m̘͟͡p̢͙̲̖a͇̯̖̺t̴̳̥̘͈͍í͓̗̘̳͉̫b̞͍͇͙ͅi̙͚̩͟l̲̕i̢̜͔̗͇̙t͎̞̦͎͖͟y̵̡̘̠̘͚̠̜͠???


Yeah N is good
