### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by kirbyfan64** [phase/o#26]
Right now, there are these files in the repo:

- `Makefile`: does this even work? I don't think so...
- `system.properties`: I think this is leftover Java crud.
- `configure-heroku`: This would need some major changes for the Python IDE.

**Comment by phase** [comment]
I think we can just delete all of those.

**Comment by phase** [comment]
Clean as of https://github.com/phase/o/commit/593d72a1aee049ab8955a8f73a13c6ba620579b4. Do you want to put the code into *src/* and separate it into different files? I think that would make it cleaner.

**Comment by kirbyfan64** [comment]
@phase I don't think that's really necessary, since it's only 2 files: `o.c` and `ide.py`.
