### ISSUE TITLE
Macro Golfing Feature Requests

### ISSUE THREAD

**Issue by kirbyfan64** [phase/o#28]
After golfing stuff in O for a bit, here are a few ideas I have for macros or macro-like things:

- `B` would be a half-macro. Basically, `BX` would basically be the same thing as `{X}`.

- Some operator to pop a result from the last stack and put it in the current one. An example helps here: currently, say we want to make an array that contains the top of the stack. If the stack is `[1]`, the array created should be `[1]`. The shortest way right now is `K[K]`, which wastes a magic variable.

    My idea is an operator (maybe `$`?) that pops an element off the previous stack and puts it in the current one. That way, the example could be shortened to just `[$]`.

**Comment by phase** [comment]
Great ideas! Any golfing ideas you have you can just implement, as you're a lot better at it than I. :stuck_out_tongue_closed_eyes:

* `B` is already being used for pushing 11, so we could either get rid of the hex numbers (which would allow us more characters to use) or choose a different character.

* So.. `5[$.*o]` ..would output `25`?

**Comment by kirbyfan64** [comment]
@phase

- Ok; screw `B`. How about `L` (for lambda)?

- Yup!

**Comment by phase** [comment]
`L` seems good, but would it just put the next amount of code into a block? Like `L1JJ+o` would _really_ be `{1}JJ+o`?

**Comment by kirbyfan64** [comment]
@phase That was the idea. Do you have a suggestion?

**Comment by phase** [comment]
If `L` isn't being used for anything then I think it's good :+1:
