### ISSUE TITLE
Can't reference variables inside a code block

### ISSUE THREAD

**Issue by adituv** [phase/o#3]
When attempting to reference a variable inside a code block, it is instead pushed onto the stack at the time of the code block's generation; my intuitive understanding was that the entirety of a code block is left unevaluated until called either by referencing its bound name or used in a control flow structure.

A cut-down example: `i:T{T}` with input `d` yields a stack of `[d,d,{}]` rather than `[d,{T}]`.

Possible fix: bump codeblock logic to the top of `O.parse` so it takes precedence over variables being dereferenced.

**Comment by phase** [comment]
This was also broken for Strings. [Fixed](http://o-lang.herokuapp.com/link/code=i%3AT%22%7BT%7D&input=d)
