### ISSUE TITLE
New lines are included in multiple inputs in IDE

### ISSUE THREAD

**Issue by phase** [phase/o#30]
With inputs setup like this:
```
1
2
3
```
And this code:
```
ioioio
```
We get this:
```
1
2
3
```
Instead of this:
```
123
```

**Comment by ConorOBrien-Foxx** [comment]
You probably have a newline output in the `o` command. ;)

**Comment by phase** [comment]
@ConorOBrien-Foxx That was my first thought, but then I tried `ipipip` (which does print with a new line), and I got this:
```
1

2

3

```

**Comment by red-green** [comment]
Possibly originating here: https://github.com/phase/o/blob/master/o.c#L183

**Comment by kirbyfan64** [comment]
At first glance, I have *no* clue where an extra newline is coming in. Let me see...

**Comment by phase** [comment]
@red-green I believe it's something at https://github.com/phase/o/blob/b722f2b9ab1ee4e9a263311e639b0504e58cedf4/o.c#L42

When it reads the inputs, it has to iterate over the characters and check for a new line. I think it's just accidentally adding it to the input itself.

**Comment by phase** [comment]
@kirbyfan64 Remove the `if(r[z-2]=='\n')` seems to work [o.c#L42](https://github.com/phase/o/blob/b722f2b9ab1ee4e9a263311e639b0504e58cedf4/o.c#L42).

**Comment by kirbyfan64** [comment]
Reason:

The issue was NOT in `po`. Basically, Flask seems to treat newlines the Windows way: `\r\n`. When that was passed to O, it only stripped the `\n`. So, the input string `1\r\n` would be `1\r`. When it was printed, the `pre` formatting in `templates/code.html` interpreted the `\r` as a newline (OSX-style).

All to say that newlines are freaking hard.

**Comment by phase** [comment]
:clap:

**Comment by red-green** [comment]
`string.strip()` ?

**Comment by kirbyfan64** [comment]
@red-green Something like `string.replace('\r')` would have also worked (since `strip` doesn't work on chars in the middle), but the real issue was the C interpreter's carriage return handling. The same issue would've occurred with `i` on Windows.
