### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by phase** [phase/o#32]
The current "_logo_" (if you can even call it that) took me 45 seconds in Paint.NET and looks like I puked up a bunch of Fruit Loops.
![gross](https://raw.githubusercontent.com/phase/o/master/static/img/logo.png)

**Comment by minxomat** [comment]
[There, now it's art](https://www.google.com/search?q=there+now+it%27s+art):

![](http://h33.imgup.net/ologod066.png)

**Comment by phase** [comment]
@minxomat I like it, but it needs more **pazaz**

@ararslan found these neat images:

![cool](http://www.johnkanesmith.com/wp-content/uploads/2010/09/alphaBattle-o.jpg)
This one is cool. I'd like to go for a non-euclidean shape.

![meh](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Sign_language_O.svg/2000px-Sign_language_O.svg.png)
This one is alright but not as cool.

**Comment by Hipe99** [comment]
What about the one in the description? You know, [will edit in picture here within 5 minutes.]

**Comment by phase** [comment]
@Hipe99 That'd be cool. I'd like an orangish-redish one.

**Comment by Hipe99** [comment]
You mean like <img src="http://surfaces.gotfork.net/project_album/red%20mobius%20strip.png" alt="red mobius strip" ></img>?

**Comment by phase** [comment]
@Hipe99 That's more like a ribbon than a non-euclidean O

**Comment by Hipe99** [comment]
It's a mobius strip, the surface is non-euclidean.

**Comment by ararslan** [comment]
I have an idea, basically a more circular red version of the big blue one I found. I'll see if I can sketch it out soon.

**Comment by phase** [comment]
@ararslan oh yes please yes please
