### ISSUE TITLE
File extension

### ISSUE THREAD

**Issue by Hipe99** [phase/o#36]
The `.o` extension is [already in use](http://www.file-extensions.org/o-file-extension), and it is fairly common (e.g. gcc -c). Perhaps `.olng`?

**Comment by phase** [comment]
I haven't actually written an O program in a file for a while... The interpreter doesn't check what the file extension of your input is, so you could use anything. I think `.olng` is a little long considering the interpreter doesn't care about it.

**Comment by ConorOBrien-Foxx** [comment]
I suggest `.og`, for "original" and for "O golf"

**Comment by Hipe99** [comment]
That seems good. As far as I know, the only other thing that uses `.og` is the outdated Atari Jaguar, discontinued in 1996.

**Comment by kirbyfan64** [comment]
Sounds kinda like `.ogg`, though.

What about `.oc` (for "O code")?

**Comment by Hipe99** [comment]
Just as obscure (apparently you can want to compile into a finite automaton?), used for [automaton](https://en.m.wikipedia.org/wiki/Nondeterministic_finite_automaton) files made by a compiler of a weird, obscure and extremely non-turing-complete language, Esterel. (It is less powerful than Perl regexs!)

**Comment by phase** [comment]
Some ideas I had:

* `oic` for *O Interpreter Code*
* `ol` for *O Language*
* `ogc` for *O Golfing Code*

**Comment by ConorOBrien-Foxx** [comment]
I like `ogc`; `ol` reminds me of the HTML element and `oic` of the acronym.
