### ISSUE TITLE
Implement %

### ISSUE THREAD

**Issue by kirbyfan64** [phase/o#42]
@phase Do you have any objections to using submodules to include [libregexp](https://github.com/0intro/libregexp)?

**Comment by phase** [comment]
We need something that works on all OSes. If that does the trick than we're good tomgo.

**Comment by kirbyfan64** [comment]
@phase [Yup](https://github.com/0intro/libregexp/issues/1)!

This might actually work surprisingly well, since libregexp comes with a simple Unicode character system that looks about good enough for the Unicode issues uncovered by #40.

**Comment by kirbyfan64** [comment]
@phase Would you like to use a submodule for libregexp, or tell people to download it separately?

**Comment by kirbyfan64** [comment]
Well, I *thought* this would be easy, but there are a bunch of weird issues, so this *might* take a bit longer than I was hoping...
