### ISSUE TITLE
Implement /

### ISSUE THREAD

**Issue by phase** [phase/o#43]
Division is not there?!?!?!

**Comment by phase** [comment]
When dividing by 0 occurs, it'd be nice to throw a `division by 0` error

**Comment by phase** [comment]
Also, this splits strings by a delimiter. [Java implementation](https://github.com/phase/o/blob/java-interpreter/src/xyz/jadonfowler/o/O.java#L385)

**Comment by kirbyfan64** [comment]
@phase The string division is there, but I forgot to actually bind it to the `/` operator...oops...

**Comment by kirbyfan64** [comment]
Almost done with this. Just need to fix some really weird corner cases.
