### ISSUE TITLE
String escaping

### ISSUE THREAD

**Issue by phase** [phase/o#44]
Characters that need escaping:
* `"`
* `'`
* `\n`
* `\t`

These also need to work with characters, i.e. `'\'o` prints `'`

**Comment by Hipe99** [comment]
How about the other standard [escape characters](https://en.wikipedia.org/wiki/Escape_sequences_in_C)? You could either go "nah, nobody uses 'em" or implement them just in case.

**Comment by phase** [comment]
@Hipe99 We'll add them all!
