### ISSUE TITLE
Function calling with arguments

### ISSUE THREAD

**Issue by phase** [phase/o#46]
I think we can use `x`, `y`, and `z` as arguments to functions (modified CodeBlocks).

```
3|xoyozo}    Creates function with 3 arguments, printing each one.
:V;               Assigns function to variable V
123V           Calls function with 1, 2, and 3
```
I don't know how useful it could be since we already have CodeBlocks that can get values from the stack.

**Comment by kirbyfan64** [comment]
So `x`, `y`, and `z` would magically transform the code block into one that takes arguments? Sounds cool!

Only issue I'm seeing is implementing it. It'd be really easy to do initially, but there are a lot of corner cases like `{1:xp'xp}`, which should print `1\nx\n`.

**Comment by phase** [comment]
I think these types of functions goes against stack orientated languages. This also just waists bytes by using special formatting and special variables. Closing _for now_
