### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by kirbyfan64** [phase/o#48]
Yay, quicksort... :/

**Comment by kirbyfan64** [comment]
@phase What letter should I use? I was thinking `s` for a normal sort. If the TOS is a code block, then it could sort the next element by the code block.

**Comment by phase** [comment]
@kirbyfan64 Oh yeah that sounds great :D

**Comment by kirbyfan64** [comment]
Fixed by https://github.com/phase/o/commit/fcbb21a5e99e87c12d5e91bf3d9f1410a75bb0ec.
