### ISSUE TITLE
+ on an array should infer the result type

### ISSUE THREAD

**Issue by kirbyfan64** [phase/o#5]
This:

```
["abc""def"]+o
```

outputs `0`, although I would expect it to output `abcdef`. This *really* sucks when you're trying to join an array of strings, since then you have to do. something like:

```
["abc""def"l1-{+}d]
```

I could try to make a PR, but I tend to [suck at building Java code](https://github.com/Cain93/WumpusHunters/issues/1), and the weird import errors I'm getting when trying to build O reflect that. :/

**Comment by phase** [comment]
This was a flaw on the design of the array folding. It's only checking for numbers in the array. I'll add it in later...
