### ISSUE TITLE
Array Arithmetic

### ISSUE THREAD

**Issue by phase** [phase/o#50]
* `[234]3+` should add 3 to each element in the array.
* `[679]2-` should subtract 2 from each element in the array.
* `[248]2*` should multiply each element in the array by 2.
* `[369]3/` should divide each element in the array by 3.

**Comment by kirbyfan64** [comment]
Ooooh, I'm claiming this! It sounds fun! :D

**Comment by phase** [comment]
This also applies for `^`, `%`, and other math operators. I also think an operator for checking if an object is in an array would be nice, but I don't know what character we could overload.

**Comment by kirbyfan64** [comment]
@phase `<`?

**Comment by phase** [comment]
That could also be used for determining if one array is bigger than another.

* `[123] 3 <o` prints _1_ because _3_ is in array _[1, 2, 3]_.
* `[1234] [123] <o` prints _0_
* `[1234] [123] >o` prints _1_

**Comment by kirbyfan64** [comment]
@phase By bigger, you mean bigger lengthwise?

**Comment by phase** [comment]
Yes :+1:

**Comment by phase** [comment]
`[456]>` would leave the stack like `[45] 6`; it pops a value off of the array and pushes it to the stack.

**Comment by kirbyfan64** [comment]
Almost done! All that's left is `[123]1<`.

**Comment by kirbyfan64** [comment]
@phase This can *finally* be closed!
