### ISSUE TITLE
Floats print with too many zeros

### ISSUE THREAD

**Issue by phase** [phase/o#51]
`3.4` will print as `3.400000`. [Test case](http://o-lang.herokuapp.com/link/ag==/My40MzU=)

**Comment by phase** [comment]
@kirbyfan64 ![random decimal points?](http://i.imgur.com/CE9vKKx.png) Now a random decimal point will be placed on really big numbers. [This was found by running Fibonacci 20 times](http://o-lang.herokuapp.com/link/MEpwMUtwantLOlZKKzpLcFY6Sjt9ZA==/NjA=)

**Comment by kirbyfan64** [comment]
@phase Ah, I know what's wrong! Hold on a sec...
