### ISSUE TITLE
Rewrite JavaScript in some other language

### ISSUE THREAD

**Issue by phase** [phase/o#53]
JS is ew, and the explanation is completely messed up and out of date. All of it needs fixing right away in some new language like Dart or TypeScript.

**Comment by kirbyfan64** [comment]
Dart is pretty awesome...assuming you don't mind long-ish, 5-second compile times.

Usually, when I'm doing simple scripts, I use CoffeeScript; with anything bigger, I use Dart.

Also, maybe there could be a script or something to auto-generate a JavaScript explanation map from commands.md? To avoid it falling out-of-date again...

**Comment by phase** [comment]
I'd love to write Dart but the compiler doesn't support 32bit :cry: 

I've started on a CoffeeScript parser, it's an... interesting language.

**Comment by kirbyfan64** [comment]
@phase Huh? I just looked at the Dart download page, and there are definitely 32-bit OS downloads!

**Comment by phase** [comment]
@kirbyfan64 
> Note: You can write Dart apps using any recent version of Windows, Linux, or Mac. The Dart development tools **do not support Windows XP.**

That's what it was ;-;

**Comment by kirbyfan64** [comment]
@phase Man, you need to try Linux or something! :D

**Comment by phase** [comment]
@k
