### ISSUE TITLE
Foreach Loops

### ISSUE THREAD

**Issue by phase** [phase/o#54]
Foreach Loops (or whatever you want to call them) are a super useful feature in every other programming language, so let's implement it!

Here's my idea:
```
[1234]{no}u

`u` goes through each element in an array 
     and runs a codeblock with the variable 
     `n` being the current element

[1234] Pushes array with 1234
{no}     CodeBlock to print each element
u         Iterate over array
```

**Comment by kirbyfan64** [comment]
Why not overload on `d`, too? That way it will save a character.

**Comment by phase** [comment]
Iterating over strings without splitting them would save a character.
```
   "test"{np}d
t
e
s
t
```

**Comment by kirbyfan64** [comment]
@phase I finished this, since this has been open for a few months...
