### ISSUE TITLE
Error in `./oide': double free or corruption (fasttop): 0x0000000000652090

### ISSUE THREAD

**Issue by phase** [phase/o#55]
Got this error when running
```
{\.@\.5**+mq.m[=}J;
j4J\4_J@+1>:F;
45*J\45*_J@+1>:L;;
FL+"Travis"N?F0>L0=+"Ness"N?L0>F0=+"Lucas"N?F0=L0=+"Pippi"N?
```
with an input of _2_. If you try to run it again, it will either give the same message or return an Internal Server Error.

/cc @kirbyfan64

**Comment by kirbyfan64** [comment]
That's a really long test case... :O

**Comment by kirbyfan64** [comment]
This was definitely caused by daeceba093237f62f5e296077e91320b52e160de. Seems to be some sort of double-free.

**Comment by kirbyfan64** [comment]
Well, this was my fault. `git bisect` says the first bad commit is 5fe512c4d5b35f009144e21c14da01b45aa2fe52.

**Comment by phase** [comment]
Yes, I didn't screw everything up!

**Comment by kirbyfan64** [comment]
@phase Well, this was actually both our faults.

There was a bug in your code in https://github.com/phase/o/commit/daeceba093237f62f5e296077e91320b52e160de: if the resulting wasn't a code block, it would be pushed onto the stack. But then, when I did https://github.com/phase/o/commit/5fe512c4d5b35f009144e21c14da01b45aa2fe52, I had it delete both `t` and `f`. If it had been pushed onto stack, then the deletes would delete the object...while it was also on the stack! So it would eventually end up being deleted TWICE.

Yay for bug hunting! :D

**Comment by kirbyfan64** [comment]
A smaller test case was `101?`.
