### ISSUE TITLE
Dictionaries

### ISSUE THREAD

**Issue by kirbyfan64** [phase/o#56]
Java O had them. C O doesn't!

I would recommend using some sort of data structure library to avoid writing YACHT (Yet Another Crappy Hash Table); maybe [libds](http://eigenstate.org/libds)?

**Comment by phase** [comment]
I didn't like the syntax for them in the old interpreter. It was buggy and didn't look good.

**Comment by phase** [comment]
We could introduce a new object, an _entry_ or _association_ that would be like a variable, but would sit on the stack and you could manipulate it. A dictionary would then be just an array of entries.

**Comment by kirbyfan64** [comment]
@phase Whoops, sorry I missed that message. That actually sounds really neat!

Here's a more concrete idea based on that:

- Add some kind of indexing operator (I was thinking `)`, since it only works on integers at the moment). When given an array, it gets an value. However, if the index is a *string*, then it searches the array for the first entry with the string value as its key. In addition, when given *just* an entry, `(` could get the key, and `)` could get the value.

- Add a "set" operator. (Maybe `=` could be overloading for this when given an array *and* a string, since that currently returns `0` anyway.) It finds the first entry in the array and sets its value to the given one. If there is no entry in the array with the key, then it adds a new entry.

- Maybe `c`, when given a string and any other object, could create an entry manually? Not sure how useful it would be, but maybe it could work.

**Comment by phase** [comment]
We've got `&` for indexing:

```
>>> [123]1&o
2
```

We could make it work with strings:

```
>>> ['a1c 'b2c 'c3c] 'b &o
{"b": 2}
```

The setting sounds good, `c` too.

**Comment by kirbyfan64** [comment]
@phase That sounds great. :)

**Comment by kirbyfan64** [comment]
Maybe the special syntax could be a bit more general:

`c` already creates entries. Maybe, when given an array, it will convert every string-and-object pair into an entry. For instance:

```
>>> ['a1'b2]c
[{a: 1, b: 2, c: 3, d: 4}]
```

That way, we don't use up another key combo.

Also, I was thinking the output could leave off the quotes, since dictionaries would only be able to hold strings.

**Comment by phase** [comment]
Why should dictionaries be limited to strings? I think any object as a key would be useful.

**Comment by kirbyfan64** [comment]
@phase Good point, but the issue is indexing. If a dictionary is just an array of entries, then `&` won't work at all with string keys, since it indexes arrays normally. Maybe we need another operator...

**Comment by phase** [comment]
Or overload that operator.

**Comment by kirbyfan64** [comment]
@phase Actually, using `c` was a stupid idea...

Since it already converts integers to characters, it would be impossible to tell whether or not to create an entry with an integer as the value or just convert an integer to a character.

Maybe we could use `t`, for en**T**ry?

**Comment by kirbyfan64** [comment]
Whoops, already done.
