### ISSUE TITLE
Error in `./oide': free(): invalid size: 0x0000000001b7aed0

### ISSUE THREAD

**Issue by kirbyfan64** [phase/o#57]
Running `H._mr]{[Q.*{nQ-}d]pn0>}%` crashes.

**Comment by phase** [comment]
Doesn't seem to be crashing on the webIDE

**Comment by kirbyfan64** [comment]
@phase I found it out from the web IDE! Try it with an input value of 24 or highter.

**Comment by kirbyfan64** [comment]
*higher*

**Comment by phase** [comment]
I'm going to guess it has something to do with the arrays you're making.

**Comment by kirbyfan64** [comment]
@phase Woah, I doubt that's the issue. The error signifies memory corruption. All upping the stack size will do is hide the real error (which seems like either a double free or some kind of overflow).

I need to run it under Valgrind, but I can't right now, as I'm on a mobile phone.

**Comment by kirbyfan64** [comment]
:O This was totally my fault!

In `o.c`, there's [this line in `tos`](https://github.com/phase/o/commit/43dd9bd1abfe71a3dc561f5f2e64e5400ee9f079#diff-81d78cf95089bf7058db37fd1f0f96e4R58):

```c
case TA:r=alc(BZ)/*XXX:overflow potential here!again!*/;r[0]='[';r[1]=0;I l=len(o->a);if(l){I i;for(i=0;i<l;++i){
```

Guess what? IT OVERFLOWED!! I need to just dynamically resize the target buffer.
