### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [phase/o#62]
I'm not sure where else to post this, but in [this](http://o.readthedocs.org/en/latest/the-basics.html?highlight=variable), you have a typo:

> Another cool feature of O is that the stack contents will **pe** outputted when the code finishes execution. Meaning ``1234`` will output ``1234``, while ``1234oooo`` will output ``4321``. This feature does not work in the REPL.

Should be

> Another cool feature of O is that the stack contents will **be** outputted when the code finishes execution. Meaning ``1234`` will output ``1234``, while ``1234oooo`` will output ``4321``. This feature does not work in the REPL.

Also, your double accent marks break the ReadTheDocs site (i.e. they don't work)

**Comment by phase** [comment]
I noticed that a couple days ago, I'll get it fixed soon. I think I'm just going to restructure that whole section to account for the new I/O changes.
