### ISSUE TITLE
Recursion in CodeBlocks

### ISSUE THREAD

**Issue by phase** [phase/o#63]
Recursion would be useful.
```
0J; {J5< LK {J):Jo} ?}K; K
Should count up to 5
```

**Comment by kirbyfan64** [comment]
Wait, so recursion is only disallowed if the code block was assigned to a builtin?

**Comment by phase** [comment]
I didn't think about that... Maybe we can have some *recursion* operator, or just disallow recursion for builtins. I think that is the best way to go.

**Comment by kirbyfan64** [comment]
@phase Yeah, disallowing recursion for builtins would definitely be easiest.
