### ISSUE TITLE
O's esolang page is outdated

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [phase/o#64]
[Esolang page](http://esolangs.org/wiki/O)

I didn't edit anything, because I'm not sure if the information is correct. Problems:
 1. O is written in C, not Java, right?
 2. The file extension isn't `.o` anymore.

**Comment by Hipe99** [comment]
It seems it has been fixed?

**Comment by ConorOBrien-Foxx** [comment]
Yeah, it surely has been
.
