### ISSUE TITLE
Jump Command

### ISSUE THREAD

**Issue by phase** [phase/o#67]
Putting code in loops can get big, so why not have a jump command? I was thinking `R` would be good.

**Comment by kirbyfan64** [comment]
How exactly would this work?

**Comment by phase** [comment]
Pop a number off the stack and go to that position in the code. Or maybe two numbers because it's two dimensional source code.

**Comment by Hipe99** [comment]
By position, do you mean character?

**Comment by kirbyfan64** [comment]
Side note: this is *way* more complicated than it seems, since you have to handle things like jumping into strings and arrays and code blocks (what happens when you do `4R"abcdefg"`?).

**Comment by phase** [comment]
@Hipe99 Yes, the character with the position popped.

@kirbyfan64 I think that's a good "feature" to have. `"1o1R"1R` would push a string to the stack, then jump inside that string and print _1_ over and over. Using parts of strings as code could be useful for compressing stuff.

**Comment by kirbyfan64** [comment]
@phase Very true. What did you mean by 2-dimensional? I thought O was 1-dimensional...

**Comment by phase** [comment]
The row and column in the source code.

```
  0123456789
0 1o
1 "hi"o
```

**Comment by Hipe99** [comment]
eh, do newlines count for anything?

**Comment by jamen** [comment]
Essentially a goto operator?  I also think it should be done linearly not via line and column.  IMO a language rarely needs to use that short information internally besides for debugging, unless it is based around it somehow (which would be annoying).

**Comment by phase** [comment]
I'm not to keen on the idea now. If we have to use manual jumps instead of the control flow operators that are built in, we're using the language wrong.
