### ISSUE TITLE
Enforce an upper recursion limit

### ISSUE THREAD

**Issue by kirbyfan64** [phase/o#70]
Right now, something like `{J}JJ` will just segfault the interpreter. @phase Do you have an idea of an upper limit? Python uses 1000, though that may be a bit too low for code golf. I'm guessing around 10,000 should work?

**Comment by phase** [comment]
```
2^13	 8192
2^14	 16384
2^15	 32768
```
An arbitrary power of two would be cool. `16,384` would be good.

**Comment by kirbyfan64** [comment]
@phase Unfortunately, I had to use 2^13 instead: 2^14 was too big, and it still segfaulted.
