### ISSUE TITLE
hi, can you read this? no jokes this about gravitation.))

### ISSUE THREAD

**Issue by vitalymay19** [phase/o#76]
Maybe you're right maybe you wrong, I review the project and mine heart is stopped in 2019 in 2015 my soul was stolen and life was broken, sorry can you fork this and remove duplicate information from mine repositorie https://github.com/vitalymay19/o
and get from them more expensive informatio, i the past i am omnidirectional RoR developer, font-end, back and all what is web, i the past becouse i am dead now, real dead, so the "o" is language of nature, 99.9% intuition that we can describe with one symbol all what we see and have, "o" = "c", "n", "u", "c" - in revers, with this 5 symbols we can generate 120 words with "5" symbols, + with 4, + with 3 ...., "o" is circle, is not zero its "1",just investigate mine repository in him many justions, is 0 = 100% or = 1, for example if we have object this object = is this 100% if need to calculate something we can write 00 = 2 and 0 0 where " " - space will be. "."
now we must translate 1.1 what its, if 1.1 its half of object then its will be 0.5, or use just a spaces like "*", by th logic if get number and make wolwinf with them(like when wolf need to kill couple of lions)  for example if we have some count of lifes, males and famales and childs(this like inoplanetains like animals) and we must get the number how much male and famele and shemales and anothers, if what we investtigate the question then this object "o" where "o" = 1 objects, in result this object must have numbers, as the question have number 100% like object then more we will investigate sex gender and put correlation in the question obejct then more we will aprove the question on 100% when its will be 100% we must record the data its like "oop" with "observers", we have some action send to the circle and investiagte,  i am not in status to ivestigate becouse i am dead, if we will use " " for "*" its will be stupid, iif we investiagte the space half of them will be 0 0 0 myabe its will be 1/3 and 1/1000 will be 0 0000 if the 0000 0 will be 10001, i think to answer the question how need to calculate need took the microskops or video on youtube and wath how moleculus moves its like physicts at left now will be larger object and in the in the right will be small object then in reverse "0000 00", "00 00000" in the and you will know that our computers is sheet thi language anothers use to investigate the gravity, and sorry for mine english, and need to remeber that circle describe normals and not normals, its like true|false, bad|god, and our choose and random sitiation to sue with the law eye by eye and 50%/50%, when someone can protect them self or anothers not in status less then 50% or can? to be always true need to write my information maybe true on 0% or more %, in theory the molecular mass of objects have some numbers, this numbers must be something like this 1.22229,222,8% of nothing we must write and send to the computers something like this 0 000 0 0 00 0, it's like a clue, think maybe nothing is "o" but also have a weight, if creatures what in mine body dont lied and they walks a trought the times, but i think that they just killing childs from that world, and make illuzion that its real to walk in time, and they just make teleportation from point "a" to "b" where "b" is mine body, if just telopration then they make the genocide, you must just imagined that on that world is just anarchy, and the goal to recover our souls from phones from another's phones.

https://github.com/vitalymay19/o

**Comment by refi64** [comment]
What the fuck
