### ISSUE TITLE
Array folding type inference

### ISSUE THREAD

**Issue by phase** [phase/o#8]
#5 but for `* / % ^ -`

CC:
@kirbyfan64

**Comment by kirbyfan64** [comment]
Ok, so I was bored and rewrote parts of O in APL-style C code. For this, I ended up solving it in a way kind of like this (in Python, since I can't code Java off the top of my head right now :):

```python
def handle_add(a, b):
    # Code for adding two items goes here
    return result # or whatever

def generic_op(the_stack):
    # Generic op handling code
    b = the_stack.pop()
 
```

**Comment by phase** [comment]
@kirbyfan64 APL-style C code? :confounded:
I don't know what purpose `*` and `/` could have on arrays, but I think `^` could be a sort of insert.

```
$ ["abc" "d"]^o
adbdcd
$ ["abc" "def_"]^o
adef_bdef_cdef_
```

**Comment by kirbyfan64** [comment]
@phase

> APL-style C code?

It's not that scary...

```c
V gnop(ST s,OTF*ft){O a,b;b=pop(s);if(b->t==TA){psh(s,opa(b,ft));dlo(b);R;};a=pop(s);if(a->t==TA)TE;/*str+any or any+str==str+str*/if(a->t==TS&&b->t!=TS){O bo=b;b=toso(b);dlo(bo);}else if(b->t==TS&&a->t!=TS){O ao=a;a=toso(a);dlo(ao);}psh(s,ft[a->t](a,b));dlo(a);dlo(b);} //generic op

O muls(O a,O b){S r,p;I i,t=b->d/*truncate*/;L z=a->s.z*t;p=r=alc(z+1);for(i=0;i<t;++i){memcpy(p,a->s.s,a->s.z);p+=a->s.z;}r[z]=0;R newosk(r,z);} //mul strings
O muld(O a,O b){R newod(a->d*b->d);} //mul decimal
V mul(ST s){O a,b;b=pop(s);if(b->t==TA){while(len(b->a)>1)mul(b->a);psh(s,dup(top(b->a)));dlo(b);R;};a=pop(s);if(a->t==TA)TE;if(a->t==TS){if(b->t!=TD)TE;psh(s,muls(a,b));}else psh(s,muld(a,b));dlo(a);dlo(b);} //mul
```

:D

> I don't know what purpose `*` and `/` could have on arrays, but I think `^` could be a sort of insert.

Very true. In reality, arrays really need more manipulative operations such as concatenation or the ability to re-open them after creation. I was guessing some overloads like:

- `(` - If TOS is an array, re-open it. (Example: `[12](3]p` prints `[1, 2, 3]`)
- `*` - Cartesian product.
- `%` - Maybe array concat?

There really should be some operator to allow moving elements on the stack into an array without having to store it in a variable first, too.

**Comment by phase** [comment]
@kirbyfan64 The array reopening should be [good to go](http://o-lang.herokuapp.com/link/code=%5B12%5D+(3%5D+p&input=).

**Comment by kirbyfan64** [comment]
@phase Dang, you're fast!

**Comment by phase** [comment]
@kirbyfan64 How should `*` work with strings?

**Comment by kirbyfan64** [comment]
@phase Sorry, I missed that comment. What exactly do you mean by that?

**Comment by phase** [comment]
@kirbyfan64 What does ["ABC" "def"]*o output?

**Comment by kirbyfan64** [comment]
Can this be closed now?

**Comment by phase** [comment]
@kirbyfan64 What else needs to be implement with arrays?

**Comment by kirbyfan64** [comment]
@phase I don't *thinkk* there's anything else...
